from mariadb.client.DataType import DataType


type_map = [None] * 256
type_map.insert(0, DataType.OLDDECIMAL)
type_map.insert(1, DataType.TINYINT)
type_map.insert(2, DataType.SMALLINT)
type_map.insert(3, DataType.INTEGER)
type_map.insert(4, DataType.FLOAT)
type_map.insert(5, DataType.DOUBLE)
type_map.insert(6, DataType.NULL)
type_map.insert(7, DataType.TIMESTAMP)
type_map.insert(8, DataType.BIGINT)
type_map.insert(9, DataType.MEDIUMINT)
type_map.insert(10, DataType.DATE)
type_map.insert(11, DataType.TIME)
type_map.insert(12, DataType.DATETIME)
type_map.insert(13, DataType.YEAR)
type_map.insert(14, DataType.NEWDATE)
type_map.insert(15, DataType.VARCHAR)
type_map.insert(16, DataType.BIT)
type_map.insert(245, DataType.JSON)
type_map.insert(246, DataType.DECIMAL)
type_map.insert(247, DataType.ENUM)
type_map.insert(248, DataType.SET)
type_map.insert(249, DataType.TINYBLOB)
type_map.insert(250, DataType.MEDIUMBLOB)
type_map.insert(251, DataType.LONGBLOB)
type_map.insert(252, DataType.BLOB)
type_map.insert(253, DataType.VARSTRING)
type_map.insert(254, DataType.STRING)
type_map.insert(255, DataType.GEOMETRY)
